src/Entity/SMSOut.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SMSOutRepository")
 */
class SMSOut
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $send_to;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    public function getId()
    {
        return $this->id;
    }

    public function getSendTo(): ?string
    {
        return $this->send_to;
    }

    public function setSendTo(string $send_to): self
    {
        $this->send_to = $send_to;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Form/SMSOutType.php
<?php

namespace App\Form;

use App\Entity\SMSOut;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SMSOutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('send_to')
            ->add('message')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SMSOut::class,
        ]);
    }
}

src/Controller/SMSOutController.php
<?php

namespace App\Controller;

use App\Entity\SMSOut;
use App\Form\SMSOutType;
use App\Repository\SMSOutRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\SendMessage;

/**
 * @Route("/")
 */
class SMSOutController extends Controller
{
    /**
     * @Route("/", name="sms_out_index", methods="GET")
     */
    public function index(SMSOutRepository $sMSOutRepository): Response
    {
        return $this->render('sms_out/index.html.twig', ['sms_outs' => $sMSOutRepository->findAll()]);
    }

    /**
     * @Route("/new", name="sms_out_new", methods="GET|POST")
     */
    public function new(Request $request, SendMessage $sendMessage): Response
    {
        $sMSOut = new SMSOut();
        $form = $this->createForm(SMSOutType::class, $sMSOut);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $form_data = $form->getData();
            // var_dump($form_data);
            $phone_no = $form_data->getSendTo();
            $message = $form_data->getMessage();

            $send = $sendMessage->sendMessage($phone_no, $message);
            $this->addFlash('success', "Message sent");

            $em = $this->getDoctrine()->getManager();
            $em->persist($sMSOut);
            $em->flush();

            return $this->redirectToRoute('sms_out_index');
        }

        return $this->render('sms_out/new.html.twig', [
            'sms_out' => $sMSOut,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sms_out_show", methods="GET")
     */
    public function show(SMSOut $sMSOut): Response
    {
        return $this->render('sms_out/show.html.twig', ['sms_out' => $sMSOut]);
    }

    /**
     * @Route("/{id}/edit", name="sms_out_edit", methods="GET|POST")
     */
    public function edit(Request $request, SMSOut $sMSOut): Response
    {
        $form = $this->createForm(SMSOutType::class, $sMSOut);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sms_out_edit', ['id' => $sMSOut->getId()]);
        }

        return $this->render('sms_out/edit.html.twig', [
            'sms_out' => $sMSOut,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sms_out_delete", methods="DELETE")
     */
    public function delete(Request $request, SMSOut $sMSOut): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sMSOut->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($sMSOut);
            $em->flush();
        }

        return $this->redirectToRoute('sms_out_index');
    }
}

templates/sms_out/_delete_form.html.twig
<form method="post" action="{{ path('sms_out_delete', {'id': sms_out.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sms_out.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sms_out/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('SEND') }}</button>
{{ form_end(form) }}

templates/sms_out/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SMSOut{% endblock %}

{% block body %}
    <h1>Edit SMSOut</h1>

    {{ include('sms_out/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('sms_out_index') }}">back to list</a>

    {{ include('sms_out/_delete_form.html.twig') }}
{% endblock %}

templates/sms_out/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Send SMS{% endblock %}

{% block body %}
    <h1>Send SMS</h1>

    <table border="1" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Send to</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sms_out in sms_outs %}
            <tr>
                <td>{{ sms_out.id }}</td>
                <td>{{ sms_out.sendTo }}</td>
                <td>
                    <a href="{{ path('sms_out_show', {'id': sms_out.id}) }}">show</a>
                    <a href="{{ path('sms_out_edit', {'id': sms_out.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sms_out_new') }}">Send new message</a><br />
    <a href="{{ path('list_messages') }}">Mpesa received messages</a><br />
    <a href="{{ path('receive_sms', {'sms_origin': '0736600033', 'message': "BS49OR20Z Confirmed.You have received Ksh20.00 from MICHAEL SOMEONE 254705285959 on 15/10/11 at 11:52 AM New M-PESA balance is Ksh100.00"}) }}">Receive a mock message</a><br />
    <a href="{{ path('clear_messages') }}">Clear all messages from mpesa table</a><br />
    {# <a href="{{ path('generate_codes', {'qty': 2000} ) }}">Generate 2000 codes</a> #}
{% endblock %}

templates/sms_out/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SMSOut{% endblock %}

{% block body %}
    <h1>Create new SMSOut</h1>

    {{ include('sms_out/_form.html.twig') }}

    <a href="{{ path('sms_out_index') }}">back to list</a>
{% endblock %}

templates/sms_out/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SMSOut{% endblock %}

{% block body %}
    <h1>SMSOut</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sms_out.id }}</td>
            </tr>
            <tr>
                <th>Send_to</th>
                <td>{{ sms_out.sendTo }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ sms_out.message }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('sms_out_index') }}">back to list</a>

    <a href="{{ path('sms_out_edit', {'id': sms_out.id}) }}">edit</a>

    {{ include('sms_out/_delete_form.html.twig') }}
{% endblock %}